---
title: Mijn camera volgt de speler niet
hero_image: images/banner.png
description: Mijn camera volgt de speler niet
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: Mijn camera volgt de speler niet
