title: My camera is not following the Player
hero_image: images/banner.png
description: My camera is not following the Player
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: My camera is not following the Player
