---
title: Ma caméra ne suit pas le joueur
hero_image: images/banner.png
description: Ma caméra ne suit pas le joueur
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: Ma caméra ne suit pas le joueur
